---
- hosts: localhost
  collections:
    - theforeman.foreman
  gather_facts: false
  vars_files:
    - vars/server.yml
  roles:
    - role: content_rhel
      vars:
        foreman_manifest_download: false
        foreman_manifest_path: "/home/rpore/manifest_OTIS-ihplin001_20241114T063625Z.zip"
        satellite_manifest_path: "/home/rpore/manifest_OTIS-ihplin001_20241114T063625Z.zip"
        foreman_content_rhel_enable_rhel7: true
        foreman_content_rhel_enable_rhel8: true
        foreman_content_rhel_sync_now: true
        foreman_content_rhel_wait_for_syncs: false
        satellite_organization: "SSE"
        username: "admin"
        password: "new42day"
        server_url: "https://ihplin001.nwcore.ssen.co.uk"
